spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
    username: root
    password: 123456

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  jpa.hibernate.ddl_auto: create
